baseURL = "https://main.d3dl1br6ocsrer.amplifyapp.com/"
languageCode = "IT-IT"
title = "Protofra.me - Il sito di Francesco Proto"
theme = "uilite"
paginate = 10
enableRobotsTXT = true
canonifyURLs = true 