baseURL = "https://main.d1q9j7vdow4326.amplifyapp.com"
languageCode = "IT-IT"
title = "Protofra.me - Il sito di Francesco Proto"
theme = "uilite"
paginate = 10
enableRobotsTXT = true
canonifyURLs = true 